### ISSUE TITLE
step by step?

### ISSUE THREAD

**Issue by qvisty** [carltongibson/neapolitan#10]
Hi Carlton

I tried using Neapolitan, but I got this error:
```
 File "C:\Users\Jesper\Documents\jq Code\djangoneapolitan\.venvneapolitan\lib\site-packages\neapolitan\views.py", line 28
    match self:
```

I am fairly noob, but could you maybe provide an even simpler "this is how you start using Neapolitan"-guide? 
Or maybe just provide me with at bit of guidance?

**Comment by carltongibson** [comment]
Can you provide the full traceback please?

**Comment by carltongibson** [comment]
Ok, I'll close. Please reopen if you have more info.
