### ISSUE TITLE
GHA: Add action to build docs. 

### ISSUE THREAD

**Issue by carltongibson** [carltongibson/neapolitan#15]
- On `main`. 
- install requirements. 
- `make json`
- Upload artifact. 

Then fetch artifact to update on server. (Webhook.)

**Comment by eduzen** [comment]
hey @carltongibson, I'm willing to help with this issue. But I was wondering how to install dependencies first. I saw that you have them in `pyproject.toml`, so I'm assuming that `pip-compile  pyproject.toml --output-file requirements.txt` is the first thing to do. Can I assume this for the pr? And also requirements?

**Comment by carltongibson** [comment]
Hi @eduzen. Installing the `docs` dependency with `pip` should be enough: 

```bash
$ pip install -e .[docs]
```

**Comment by eduzen** [comment]
Thanks, @carltongibson, you are right! I updated the status of the [pr](https://github.com/carltongibson/neapolitan/pull/20)
