### ISSUE TITLE
Delete confirm page text

### ISSUE THREAD

**Issue by kasun** [carltongibson/neapolitan#25]
The Delete confirm page's button says "Save" and it has a blue background. Do you think we can improve this page with following changes?

1. Change button text to "Delete" or something similar.
2. Change button background color to Red.
3. Change confirm text from "Confirm Delete" to something like "Are you sure you want to delete following {object_type}"?

If you agree happy to submit a PR for this.

**Comment by carltongibson** [comment]
Hey @kasun -- that would be great, thanks 🙏
