### ISSUE TITLE
User decorador and User sessions

### ISSUE THREAD

**Issue by leonardomporto** [carltongibson/neapolitan#36]
Good morning Carl. Congratulations on the work, what a practical thing. Forgive me for the newbie question, but I would like to use Neapolitan with user sessions, so that I could restrict a reading page, for example, to only logged in users, and that the display would only represent the registrations made by that logged in user. I couldn't elaborate on this, I always have a list of errors. Can you give me some light? thank you very much.

**Comment by carltongibson** [comment]
For auth you can use [`@login_required` as normal](https://docs.djangoproject.com/en/5.0/topics/class-based-views/intro/#decorating-class-based-views), for example. 

For filtering, override `get_queryset()`...

```python
class PageView(CRUDView):
    def get_queryset(self):
         return Page.objects.filter(user=self.request.user)
```

Or some such, similar.
