### ISSUE TITLE
Error due to order of Url path using Django pk as UUID

### ISSUE THREAD

**Issue by anilrai21** [carltongibson/neapolitan#60]
**Using versoin 24.6**

I found an issue when I tried to set `path_converter` as `slug` and I had set my id to be UUID.  

```
ValidationError at /product/new/
['“new” is not a valid UUID.']
```

The reason seems to be that `detail` url path comes before `create` and treats `new` string as the pk and raises this issue.

My Class looks as shown below. 

```
class Product(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=100)
    alias = models.CharField(max_length=100, blank=True)
```

My current solution is to override the `get_urls` as shown below.

```
class BaseCRUDView(CRUDView):
    path_converter = "slug"

    @classonlymethod
    def get_urls(cls, roles=None):
        roles_list = super().get_urls(roles)
        return sorted(roles_list, key=lambda role: role.name)
```

Let me know if the above makes sense.  It if does, a potential solution would be to make the sorted change in the `CRUDView` itself.

**Comment by carltongibson** [comment]
Wouldn't you need a [UUID path converter](https://docs.djangoproject.com/en/5.1/topics/http/urls/#s-path-converters) here? 🤔

**Comment by anilrai21** [comment]
You are absolute right.  I am closing this.
