### ISSUE TITLE
CRUDView.get_urls order incompatible with slug fields

### ISSUE THREAD

**Issue by SamuelJennings** [carltongibson/neapolitan#64]
Currently, `views.CRUDView.get_urls` outputs urlpatterns in a bad order for slug based lookups. For example,

```python

class TopicCRUDView(CRUDView):
    model = Topic
    form_class = TopicForm
    lookup_field = "slug"
    path_converter = "slug"

...
# urls.py
urlpatterns = [
    *TopicCRUDView.get_urls(),
]

# produces the following urls in order
# /topic/       
# /topic/<slug:slug>/   
# /topic/new/    
# /topic/<slug:slug>/edit/  
# /topic/<slug:slug>/delete/ 
``` 

Now, when a user tries to create a new topic, django will match the second url and query the DB for a topic with slug == "new", resulting in a 404. Simple fix is to reorder the roles in `views.Role` so that CREATE is listed before DETAIL.

**Comment by carltongibson** [comment]
Yes. I'd take a PR for this with a test. Thanks.
