### ISSUE TITLE
Nested pages pattern

### ISSUE THREAD

**Issue by Alex-Sichkar** [carltongibson/neapolitan#75]
Is there a common pattern for nested pages? For example, I want to include tabs within an object detail page.

Thanks in advance!

**Comment by carltongibson** [comment]
This is more of a UI question than Neapolitan specifically I think. 

I use a combination of HTMX and alpine.js for all my needs. I find they compliment Neapolitan and Django very well. 

* https://htmx.org
* https://alpinejs.dev/start-here

For tabs, you can either just include the HTML for each tab in the interface at load time, and use alpine to switch between then, or you can have each page as a separate tab, switching template on a query parameter or similar, and load them in either as full page loads or just fragments, as you prefer. (Or as suits your case.)

**Comment by Alex-Sichkar** [comment]
@carltongibson

I mean views, URL routing, and templates. So, should I create separate views and URL patterns for each tab?
Something like this:

```python
urlpatterns += BookView.get_urls()

urlpatterns += [
    path("book/<int:pk>/tab1/", views.book_tab1),
    path("book/<int:pk>/tab2/", views.book_tab2),
]
```

**Comment by carltongibson** [comment]
OK, you want to add extra handlers in your class' `get_urls()` method. 

This is custom actions, which I just need time to add. 

See the discussion on #73 which is along the right lines.

**Comment by carltongibson** [comment]
See the example here: 

https://github.com/carltongibson/neapolitan/issues/32#issuecomment-1764518627

... it shows manually configuring URLs. 

That particular example was about limiting URLs, but the same idea works for adding them.

**Comment by carltongibson** [comment]
I'll close this as a duplicate.
