### ISSUE TITLE
Show example templates using another CSS framework

### ISSUE THREAD

**Issue by carltongibson** [carltongibson/neapolitan#9]
The default templates use Tailwind, but it's not compulsory. 

An `examples/X_css` mini-project showing overriding the default would be good to have. 

Million dollar question: which framework? 😅

**Comment by dertuxmalwieder** [comment]
picocss.

**Comment by carltongibson** [comment]
@dertuxmalwieder — that's a speedy answer! Would you fancy submitting?

**Comment by dertuxmalwieder** [comment]
Not today - busy over the weekend. Bookmarked…

**Comment by carltongibson** [comment]
Good thread on Mastodon points to the survey which has Bootstrap the most used framework by far.

https://fosstodon.org/@carlton/110276421113060175

**Comment by carltongibson** [comment]
@gelie would you like to add that as a sub folder in a `examples/` dir?

**Comment by abe-101** [comment]
Is it the goal of this project to support other css framework aside from tailwind?

My project uses bootstrap so I over-road the templates with bootstrap ones
I'd be happy to open a PR with the bootrap templates - just where would they go? and perhaps there should be a setting variable where user can choose the framework

(I also used crispy-forms)

**Comment by carltongibson** [comment]
Hi @abe-101 — I think an example project overriding the core templates is what's needed, so a `bootstrap_templates` app in the `examples` folder would be perfect. 

I expect folks to copy/paste the templates into their own project rather than adding complex settings tweaks. In general I expect folks to override the templates on a per project, or per-model even, basis, rather than using the provided ones for very long. Some docs explaining this approach are probably needed here too. (Happy to help with those.)

**Comment by abe-101** [comment]
PR #72 adds a bootstrap example
